config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    # path('loja/', include('loja.urls')),

    path('admin/', admin.site.urls),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# TODO: Remover debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

produto/urls.py
from django.urls import path

from . import views


app_name = 'produto'


urlpatterns = [
    path('', views.ListaProdutos.as_view(), name='lista'),
    path('<slug>', views.DetalheProduto.as_view(), name='detalhe'),
    path('adicionar_carrinho/', views.AdicionarCarrinho.as_view(), name='adicionar_carrinho'),
    path('remover_carrinho/', views.RemoverCarrinho.as_view(), name='remover_carrinho'),
    path('carrinho/', views.Carrinho.as_view(), name='carrinho'),
    path('finalizar/', views.Finalizar.as_view(), name='finalizar'),
]

produto/models.py
from django.db import models
from stdimage.models import StdImageField
from django.utils.text import slugify
from django.utils.safestring import mark_safe
from utils import utils



class Produto(models.Model):
    nome = models.CharField(max_length=255)
    descricao_curta = models.TextField(max_length=255)
    descricao_longa = models.TextField()
    imagem = StdImageField(upload_to='fotos/%Y/%m/%d', variations={'thumbnail': {'width': 700, 'height': 500}}, blank=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    preco_marketing = models.FloatField()
    preco_marketing_promocional = models.FloatField(default=0)
    tipo = models.CharField(default='V', max_length=1 ,choices=( ('V', 'Variável'), ('S', 'Simples') ))

    def __str__(self) -> str:
        return self.nome

    

    def get_preco_formatado(self):
        return utils.formata_preco(self.preco_marketing)
    get_preco_formatado.short_description = 'Preço'


    def get_preco_promocional_formatado(self):
        return utils.formata_preco(self.preco_marketing_promocional)
    get_preco_promocional_formatado.short_description = 'Preço Promocional'


    @mark_safe
    def img(self):
        return f'<img src="/media/{self.imagem.thumbnail}" width="30px">'


    def save(self, *args, **kwargs):
        self.slug = slugify(self.nome)
        return super().save(*args, **kwargs)


class Variacao(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    nome = models.CharField(max_length=50)
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    estoque = models.PositiveIntegerField(default=1)

    class Meta:
        verbose_name = 'Variação'
        verbose_name_plural = 'Variações'

    def __str__(self) -> str:
        return self.nome or self.produto.nome

produto/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.contrib import messages
from pprint import pprint
from . import models

from pprint import pprint


class ListaProdutos(ListView):
    model = models.Produto
    template_name = 'produto/lista.html'
    context_object_name = 'produtos'
    paginate_by = 10


class DetalheProduto(DetailView):
    model = models.Produto
    template_name = 'produto/detalhe.html'
    context_object_name = 'produto'
    slug_url_kwarg = 'slug'
    


# Trata-se de um formulario
class AdicionarCarrinho(View):

    def get(self, *args, **kwargs):

        # if self.request.session.get('carrinho'):
        #     del self.request.session['carrinho']
        #     self.request.session.save()

        http_referer = self.request.META.get('HTTP_REFERER', reverse('produto:lista'))
        variacao_id = self.request.GET.get('vid')


        print(self.request.POST)

        if not variacao_id:
            messages.error(self.request, 'Produto não existe')
            return redirect(http_referer)

        variacao = get_object_or_404(models.Variacao, id=variacao_id)
        variacao_estoque = variacao.estoque
        variacao_nome = variacao.nome or ''
        preco_unitario = variacao.preco
        preco_unitario_promocional = variacao.preco_promocional

        quantidade = 1

        produto = variacao.produto
        produto_id = produto.id
        produto_nome = produto.nome
        slug = produto.slug
        imagem = produto.imagem

        if imagem:
            imagem = imagem.name
        else:
            imagem = ''


        if variacao.estoque < 1:
            messages.error(self.request, 'Estoque insuficiente')
            return redirect(http_referer)

        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = {}
            self.request.session.save()


        if variacao_id in self.request.session['carrinho']:
            quantidade_carrinho = self.request.session['carrinho'][variacao_id]['quantidade']
            quantidade_carrinho += 1

            if variacao_estoque < quantidade_carrinho:
                messages.warning(self.request, f'Estoque insuficiente para {quantidade_carrinho}x no produto "{produto.nome}". Adicionamos {variacao_estoque}x no seu carrinho')
                quantidade_carrinho = variacao_estoque

            self.request.session['carrinho'][variacao_id]['quantidade'] = quantidade_carrinho
            self.request.session['carrinho'][variacao_id]['preco_quantitativo'] = preco_unitario * quantidade_carrinho
            self.request.session['carrinho'][variacao_id]['preco_quantitativo_promocional'] = preco_unitario_promocional * quantidade_carrinho
            

        else:
            # TODO: Variação não existe no carrinho
            self.request.session['carrinho'][variacao_id] = {
                'produto_id': produto_id,
                'produto_nome': produto_nome, 
                'variacao_nome': variacao_nome,
                'variacao_id': variacao_id, 
                'preco_unitario': preco_unitario, 
                'preco_unitario_promocional': preco_unitario_promocional, 
                'preco_quantitativo': preco_unitario, 
                'preco_quantitativo_promocional': preco_unitario_promocional, 
                'quantidade': 1,
                'slug': slug, 
                'imagem': imagem, 
            }

        carrinho = self.request.session['carrinho']
        self.request.session.save()
        pprint(self.request.session['carrinho'])
        messages.success(self.request, f'"{produto_nome} {variacao_nome}" Adicionado ao seu Carrinho {carrinho[variacao_id]["quantidade"]}x')
        return redirect(http_referer)


        return HttpResponse(f'{variacao.produto} {variacao.nome}')


class RemoverCarrinho(View):
    def get(self, *args, **kwargs):

        http_referer = self.request.META.get('HTTP_REFERER', reverse('produto:lista'))
        variacao_id = self.request.GET.get('vid')

        if not variacao_id:
            return redirect(http_referer)

        if not self.request.session.get('carrinho'):
            return redirect(http_referer)

        if variacao_id not in self.request.session['carrinho']:
            return redirect(http_referer)
        
        carrinho = self.request.session['carrinho'][variacao_id]

        messages.success(self.request, f'Produto {carrinho["produto_nome"]} {carrinho["variacao_nome"]} removido do seu carrinho')

        # Removendo do carrinho
        del self.request.session['carrinho'][variacao_id]
        self.request.session.save()
        return redirect(http_referer)

class Carrinho(View):
    def get(self, *args, **kwargs):
        return render(self.request, 'produto/carrinho.html')


class Finalizar(View):
    pass

templates/produto/carrinho.html
{% extends 'base.html' %}
{% load filtros %}
{% load static %}

{% block 'content' %}

{% if request.session.carrinho %}

    <div class="row mt-3">
        <div class="col">
            <h3>Carrinho de compras</h3>
            <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

            <div class="table-responsive">
                <table class="table">
                    <tr>
                        <th class="d-none d-lg-block">Imagem</th>
                        <th>Produto</th>
                        <th>V.</th>
                        <th>QTD.</th>
                        <th>Total</th>
                    </tr>

                    {% for produto in request.session.carrinho.values %}
                   
                        <tr>
                            <td class="d-none d-lg-block">
                                <img class="cart-img" src="{% get_media_prefix %}{{ produto.imagem }}">
                            </td>
                            <td>
                                <a href="{% url 'produto:detalhe' produto.slug %}">{{ produto.produto_nome }}</a>
                                <a class="ml-3" href="{% url 'produto:remover_carrinho' %}?vid={{ produto.variacao_id }}">
                                    <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                                </a>
                            </td>
                            <td>{{ produto.variacao_nome }}</td>
                            <td>

                                {{ produto.quantidade }} x
                                {% if produto.preco_unitario_promocional %}

                                    {{ produto.preco_unitario_promocional }}

                                {% else %}
                                    {{ produto.preco_unitario }}
                                {% endif %}
                            
                            </td>



                            {% if produto.preco_quantitativo_promocional %}

                                <td>{{ produto.preco_quantitativo_promocional|preco_formatado }}</td>

                            {% else %}

                                <td>{{ produto.preco_quantitativo|preco_formatado }}</td>

                            {% endif %}

                        </tr>
                    {% endfor %}


                </table>
            </div>
        </div>
    </div>



    <div class="row mt-3">
        <div class="col-lg">
            <p class='lead'>Total no carrinho</p>

            <div class='table-responsive'>
                <table class="table">
                    <tr>
                        <td class="font-weight-bold">Total</td>
                        <td>R$100000</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="col-lg mt-auto">
            <a class="btn btn-lg btn-block btn-primary" href="#">
                Finalizar a compra
            </a>
        </div>
    </div>

{% else %}

    <div class="row mt-3">
        <div class="col">
            <h3>Carrinho vazio</h3>
            <p class="lead">Não há produtos no seu carrinho</p>

        </div>
    </div>

{% endif %}


{% endblock %}

templates/produto/detalhe.html
{% extends 'base.html' %}
{% load filtros %}

{% block 'content' %}

    <div class="row">
        <div class="col-lg">
            <div class="row no-gutters">
                <div class="col-lg-12">

                    {% if produto.imagem %}
                        <img class="img-fluid" src="{{ produto.imagem.thumbnail.url }}">
                    {% endif %}

                </div>
            </div>
        </div>

        <div class="col-lg">
            <div class="mt-4 mt-lg-0">
                <h1 class="h2">{{ produto.nome }}</h1>
                <p class="lead">{{ produto.descricao_curta }}</p>
                <p class="lead">

                    {% if produto.preco_marketing_promocional %}
                        <span id="variation-preco-promocional" class="lead product-price">{{ produto.preco_marketing_promocional|preco_formatado }}</span>
                        <span id="variation-preco" class="lead product-old-price text-muted">{{ produto.preco_marketing|preco_formatado }}</span>
                    {% else %}
                        <span id="variation-preco" class="lead product-price">{{ produto.preco_marketing|preco_formatado }}</span>
                    {% endif %}
                            
                </p>

                <form action="{% url 'produto:adicionar_carrinho' %}" id="form-add-to-cart">
                    <div class="form-group">
                        <select id="select-variacoes" name="vid" class="form-control form-control-lg">
                            {% for variacao in produto.variacao_set.all %}
                                
                                {% if variacao.preco_promocional %}

                                    <option data-preco="{{ variacao.preco|preco_formatado }}" data-preco-promocional="{{ variacao.preco_promocional|preco_formatado }}" value="{{ variacao.id }}">
                                        {% if variacao.nome %}
                                            {{ variacao.nome }}
                                        {% else %}
                                            {{ variacao }}
                                        {% endif %}
                                    
                                    </option>

                                {% else %}

                                    <option data-preco="{{ variacao.preco|preco_formatado }}" value="{{ variacao.id }}">
                                        {% if variacao.nome %}
                                            {{ variacao.nome }}
                                        {% else %}
                                            {{ variacao }}
                                        {% endif %}
                                    </option>
                                    
                                {% endif %}

                            {% endfor %}
                        </select>
                    </div>

                    <div class="text-left">
                        <button type="submit" class="btn btn-primary btn-lg btn-block">
                            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                            Adicionar ao carrinho
                        </button>
                    </div>

                </form>


            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="mt-5 mb-5">
                <h2 class="text-center">{{ produto.nome }}</h2>
                {{ produto.descricao_longa|linebreaks }}
            </div>
        </div>
    </div>

{% endblock %}

templates/produto/lista.html
{% extends 'base.html' %}
{% load filtros %}

{% block 'title' %}
    Produtos
{% endblock %}


{% block 'content' %}

    <div class="row">
        <div class="col-lg-12">
            <div class="card-columns">

                {% for produto in produtos %}
                    <div class="card">
                        
                        {% if produto.imagem %}
                            <a href="{{ produto.slug }}">
                                <img class="card-img-top" src="{{ produto.imagem.thumbnail.url }}" alt="Card image cap">
                            </a>
                        {% endif %}

                        <div class="card-body">
                            <h5 class="card-title {{produto.nome}}">{{ produto.nome }}</h5>
                            <p class="card-text">{{ produto.descricao_curta }}</p>
                            <div class="container product-price-block text-center">
                                {% if produto.preco_marketing_promocional %}

                                    <span class="product-price">
                                        {{ produto.preco_marketing_promocional|preco_formatado }}
                                        
                                    </span>

                                    <span class="product-old-price text-muted">
                                        {{ produto.preco_marketing|preco_formatado }}
                                    </span>

                                {% else %}
                                    <span class="product-price">
                                        {{ produto.preco_marketing|preco_formatado }}
                                    </span>
                                {% endif %}
                                    
                            </div>
                        </div>
                        <div class="card-footer bg-transparent border-top-light-custom text-center">
                            <a href="{{ produto.slug }}" class="btn btn-primary btn-sm m-1 btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Comprar
                            </a>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col">
            {% include 'partials/pagination.html' %}
        </div>
    </div>

{% endblock %}